name: Build and Deploy

on:
  release:
    types: [created]

env:
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "asudarchikov/test"
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "asudarchikov/test"
